# Generated by Django 3.1.7 on 2021-03-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=300)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfStart', models.DateField()),
                ('DateOfEnd', models.DateField()),
                ('Duration', models.FloatField()),
                ('RestTime', models.FloatField()),
                ('RepitionNum', models.IntegerField()),
                ('MembersToUse', models.IntegerField()),
                ('Difficulty', models.IntegerField()),
                ('Notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCreation', models.DateTimeField()),
                ('Description', models.CharField(max_length=300)),
                ('Session_Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_plan', to='physio.exercise_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Physiotherapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=150)),
                ('BirthDate', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('Photo', models.CharField(max_length=100)),
                ('PhotoPath', models.CharField(max_length=100)),
                ('Clinic_Physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pysio_therpists', to='physio.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=150)),
                ('BirthDate', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('Photo', models.CharField(max_length=100)),
                ('PhotoPath', models.CharField(max_length=100)),
                ('Gender', models.IntegerField()),
                ('Physio_Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='physio.physiotherapist')),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCreation', models.DateTimeField()),
                ('Notes', models.CharField(max_length=300)),
                ('Patient_Observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_observ', to='physio.patient')),
                ('Session_Observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_observ', to='physio.session')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Fav', to='physio.patient')),
                ('Physio_Favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Physio_Fav', to='physio.physiotherapist')),
            ],
        ),
        migrations.AddField(
            model_name='exercise_plan',
            name='Game_Exerplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game_Plan', to='physio.game'),
        ),
        migrations.AddField(
            model_name='exercise_plan',
            name='Patient_Exerplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Plan', to='physio.patient'),
        ),
        migrations.AddField(
            model_name='exercise_plan',
            name='Physio_Exerplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Physio_Plan', to='physio.physiotherapist'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=150)),
                ('BirthDate', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('Photo', models.CharField(max_length=100)),
                ('PhotoPath', models.CharField(max_length=100)),
                ('Admin_Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='physio.clinic')),
            ],
        ),
    ]
